/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package software.component.cataloging;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author R0$H4N
 */
public class DisplayComponent extends javax.swing.JPanel {

    /**
     * Creates new form displayComponent
     */
    public DisplayComponent(String type) {
        initComponents();
        showContentButton.setText(type);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        descriptionTextScrollPane = new java.awt.ScrollPane();
        usedLabel = new javax.swing.JLabel();
        unusedLabel = new javax.swing.JLabel();
        lastUsedLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        showContentButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        usedTextLabel = new javax.swing.JLabel();
        unusedTextLabel = new javax.swing.JLabel();
        lastUsedTextLabel = new javax.swing.JLabel();
        nameTextLabel = new javax.swing.JLabel();
        typeTextLabel = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();

        nameLabel.setText("Name");

        usedLabel.setText("Used");

        unusedLabel.setText("Unused");

        lastUsedLabel.setText("Last used");

        typeLabel.setText("Type");

        showContentButton.setText("Show Content");
        showContentButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showContentButtonMouseClicked(evt);
            }
        });

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        usedTextLabel.setText("    ");

        unusedTextLabel.setText("    ");

        lastUsedTextLabel.setText("    ");

        nameTextLabel.setText("     ");

        typeTextLabel.setText("   ");

        deleteButton.setText("Delete");

        javax.swing.GroupLayout displayPanelLayout = new javax.swing.GroupLayout(displayPanel);
        displayPanel.setLayout(displayPanelLayout);
        displayPanelLayout.setHorizontalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(displayPanelLayout.createSequentialGroup()
                        .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(displayPanelLayout.createSequentialGroup()
                                .addComponent(typeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(typeTextLabel))
                            .addGroup(displayPanelLayout.createSequentialGroup()
                                .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameTextLabel)))
                        .addGap(441, 441, 441)
                        .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usedLabel)
                            .addComponent(unusedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastUsedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usedTextLabel)
                            .addComponent(unusedTextLabel)
                            .addComponent(lastUsedTextLabel))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(displayPanelLayout.createSequentialGroup()
                        .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descriptionTextScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showContentButton)
                            .addGroup(displayPanelLayout.createSequentialGroup()
                                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 27, Short.MAX_VALUE))))
        );
        displayPanelLayout.setVerticalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usedTextLabel)
                    .addComponent(nameTextLabel))
                .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(displayPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(unusedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(unusedTextLabel))
                        .addGap(30, 30, 30)
                        .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastUsedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lastUsedTextLabel))
                        .addGap(71, 71, 71))
                    .addGroup(displayPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(typeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(typeTextLabel))
                        .addGap(88, 88, 88)))
                .addComponent(descriptionTextScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(showContentButton)
                .addGap(60, 60, 60)
                .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeButton)
                    .addComponent(deleteButton))
                .addGap(91, 91, 91))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(displayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_closeButtonActionPerformed

    private void showContentButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showContentButtonMouseClicked
        try {
            showContent("images/UseCase.png", showContentButton.getText());
        } catch (Exception ex) {
            Logger.getLogger(DisplayComponent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_showContentButtonMouseClicked

    public void showContent(final String u, String type) throws Exception {
        if(type.equalsIgnoreCase("design")){
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                JLabel imageLabel = new JLabel(new ImageIcon(u));
                JScrollPane jsp = new JScrollPane(imageLabel);
                JOptionPane.showMessageDialog(null, jsp, "Content", JOptionPane.INFORMATION_MESSAGE);
                displayPanel.add(jsp);
                
            }
        });
        }else if(type.equalsIgnoreCase("code"))
        {
            SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                JLabel imageLabel = new JLabel(new ImageIcon(u));
                JScrollPane jsp = new JScrollPane(imageLabel);
                JOptionPane.showMessageDialog(null, jsp, "Content", JOptionPane.INFORMATION_MESSAGE);
                displayPanel.add(jsp);
                
            }
            });
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JButton deleteButton;
    private java.awt.ScrollPane descriptionTextScrollPane;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JLabel lastUsedLabel;
    private javax.swing.JLabel lastUsedTextLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameTextLabel;
    private javax.swing.JButton showContentButton;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JLabel typeTextLabel;
    private javax.swing.JLabel unusedLabel;
    private javax.swing.JLabel unusedTextLabel;
    private javax.swing.JLabel usedLabel;
    private javax.swing.JLabel usedTextLabel;
    // End of variables declaration//GEN-END:variables
}
